### ISSUE TITLE
/usr/bin/ipgw: line 123: /(1024*1024*1024): syntax error: operand expected (error token is "/(1024*1024*1024)")

### ISSUE THREAD

**Issue by zsxgb** [cool2645/neu-ipgw_linux#3]
/usr/bin/ipgw: line 123: /(1024*1024*1024): syntax error: operand expected (error token is "/(1024*1024*1024)")

**Comment by rikakomoe** [comment]
请问这个问题是在正常情况下还是断网的情况下出现的（能否正常使用）？

**Comment by zsxgb** [comment]
都有的

**Comment by zsxgb** [comment]
不能正常使用

**Comment by rikakomoe** [comment]
这个发生时是提示 网络连接成功还是失败 同时从 ipgw 的网页 portal 能不能登录

**Comment by zsxgb** [comment]
只用网页是可以登录的。用这个工具就会报错。只有我一个人么。你的没问题??

**Comment by rikakomoe** [comment]
需要向计算中心的老师确认 ipgw 今后的动向

**Comment by rikakomoe** [comment]
似乎 https 是没问题的 这边证书验证的问题
